### ISSUE TITLE
指标数据mAP ，R-1保存在哪里？

### ISSUE THREAD

**Issue by yxx0828** [QizaoWang/DASA-LReID#1]
您好，感谢您优秀的研究！您的论文对我的帮助很大。我想向您请教一个问题：当我执行命令：CUDA_VISIBLE_DEVICES=0 python continual_train.py --training-order=1 --data-dir=DATASET_ROOT --logs-dir=LOG_DIR 后，在log.txt中只有每10个Epoch的交叉熵损失值，而没有指标mAP ，R-1的记录。请问指标是保存在哪里的？谢谢！
![2024-12-27 22-37-00 的屏幕截图](https://github.com/user-attachments/assets/202a9de4-e3bf-4889-9d17-fa1c2c99f5c6)
![2024-12-27 22-36-39 的屏幕截图](https://github.com/user-attachments/assets/8040c521-481a-4df1-af5e-75b8c85ef257)

**Comment by QizaoWang** [comment]
您好，感谢对我们工作的认可，请使用更新后的代码。

**Comment by yxx0828** [comment]
您好，感谢您的回复，请问可以提供一下cuhksysu4reid数据集吗？谢谢！

**Comment by QizaoWang** [comment]
您好，README中已经说明了获取方式，详情请遵循AKA这篇工作的代码仓库。
